### ISSUE TITLE
Configuration needed

### ISSUE THREAD

**Issue by marcinbojko** [juanpabloaj/phoenix_gitlab_monitor#7]
Any kind of extending possibility by adding configurations would be nice - for example:
- how long should I display message?
- how long display success/failed?

**Comment by juanpabloaj** [comment]
Hi @marcinbojko, thanks for your message.

Do you have some ideas about where could be the best place to add those configurations?
I tried to avoid to add a place like a dashboard to set those type of configurations.

Thanks again.

**Comment by marcinbojko** [comment]
Hi @juanpabloaj .
I succesfully started your project on both: docker-compose and kubernetes-rancher, so if possible simple yaml/json available at start level would be great.
As you mentioned, adding stuff on dashboard level would require lots of new features: storing config somewhere, validation, authentication/authorization.
If, this file could be readable and available during container/application start I think that would solve some problems.
Thanks for great idea - thanks you you, within minutes i am able to see what's going on ;)
