### ISSUE TITLE
Extend information in display boxes

### ISSUE THREAD

**Issue by marcinbojko** [juanpabloaj/phoenix_gitlab_monitor#8]
Current information presents data of last commit's user. But, in pipelines repositories, sometimes config doesn't change often and the only changing information is: pipeline number, date when pipeline started, date/time when pipeline ended and user/webhook who initiated pipeline.
I'd vote for possibility to replace last commit user with 'triggered by' data.

**Comment by marcinbojko** [comment]
I did it completely blindly, sorry, not a dev.
https://github.com/juanpabloaj/phoenix_gitlab_monitor/pull/9

The effect:
![image](https://user-images.githubusercontent.com/4726723/63798262-0b6c1780-c90a-11e9-81ab-8e61e4aedf6e.png)

**Comment by juanpabloaj** [comment]
@marcinbojko with your pull request now the username is available, thanks.

I moved the triggered line to the paragraph, 

![triggered_by](https://user-images.githubusercontent.com/732415/64068109-6dc26200-cc01-11e9-838d-73a3995a516b.png)

If you agree, please close the issue.

thanks again.

**Comment by juanpabloaj** [comment]
I released a new tag 0.3.0 with your changes, in a few minutes the new image will be available.

**Comment by marcinbojko** [comment]
Thank you - your version looks much more nice than mine :)
Thanks!
